config/routes.rb
SchoolApp::Application.routes.draw do
  devise_for :admins
  
  root :to => "home#index"
  
  match '/pages/:id' => 'pages#show'
  
 
   match '/content' => 'pages#content'
  match '/pages/pages/:id' => 'pages#show'
  match '/admin/pages/:id/delete' => 'admin/pages#destroy'
  match '/admin/contacts/:id/delete' => 'admin/contacts#destroy'
  match '/home/:id' => 'home#contact'
   match '/contacts' => 'home#contact'
   
   namespace :admin do 
     match '/dashboard'   => "dashboard#index", :as => :root
          resources :pages
          resources :contacts
          match 'system/pages/photos/:id/' => 'admin/pages#destroy'
         
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  
  attr_accessible :email, :password, :password_confirmation
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
end

app/models/page.rb
class Page < ActiveRecord::Base
 before_validation :clear_photo
  has_attached_file :photo, 
                    :default_url => '/assets/images.jpeg'
                    

 
    def delete_photo=(value)
    @delete_photo = !value.to_i.zero?
  end
  
  def delete_photo
    !!@delete_photo
  end
  alias_method :delete_photo?, :delete_photo
  
def clear_photo
  self.photo = nil if delete_photo? && !photo.dirty?
end

end

app/models/tiny_print.rb
class TinyPrint < ActiveRecord::Base
  
  has_attached_file :image,
    :convert_options => { :quality =>  4 },
    :styles => { :small_thumb => [ "50x50", :jpg ],
	               :medium_thumb => [ "100x100", :jpg ],
                 :large_thumb => [ "370x370", :jpg ],
	               :detail_preview => [ "450x338", :jpg ] },
    #:path => "/prints/:id/:style.:extension",
    :default_url => "/images/missing/prints/:style.png"

end

app/models/tiny_video.rb
class TinyVideo < ActiveRecord::Base
  
  has_attached_file :original
  #, :path => "videos/:original/:id.:extension",

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController
  
  before_filter :authenticate_admin!, :except => []
  def index
      @pages = Page.all
    end

    def new
      @page = Page.new
    end

    def create
      @page = Page.new(params[:page])
      if @page.save
        flash[:notice] = "Pages created successfully"
        redirect_to admin_pages_path
      else
        render :new
      end
    end
    
    def edit
      @page = Page.find(params[:id])
    end

    def update
      @page = Page.find(params[:id])
      if @page.update_attributes(params[:page])
        flash[:notice] = "Pages saved successfully"
        redirect_to admin_pages_path
      else
        render :new
      end
    end
    

    def destroy
      @page = Page.find(params[:id])
     
      if @page.destroy
        flash[:notice] = "Pages deleted successfully"
        redirect_to admin_pages_path
      end
      
    end
   
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create

  def manage
    @attachments = "tiny_#{params[:media]}".classify.constantize.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10
    render :update do |page|
      page.replace_html :dynamic_images_list, :partial => 'show_attachment_list'
    end
  end
  


  def create
    @attachment = "tiny_#{params[:media]}".classify.constantize.new params[params[:media]]
    
    if @attachment.save
      GC.start
      responds_to_parent do
        render :update do |page|
          page << "upload_callback();"
        end
      end
    else
      responds_to_parent do
        render :update do |page|
          page.alert('Sorry, there was an error uploading the photo.')
        end
      end
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
      @contacts = Contact.find(:all)
    end

    def new
      @contact = Contact.new
    end

    def create
      @contact = Contact.new(params[:contact])
      respond_to do |format|
    if @contact.save
      format.html { redirect_to(@contact, :notice => 'contacts was successfully created.') }
      format.xml { render :xml => @contact, :status => :created, :location => @contact }
    else
      format.html { render :action => "new" }
      format.xml { render :xml => @contact.errors, :status => :unprocessable_entity }
    end
  end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
    
  def contact
    if request.post? and params[:reset_password]
            if contact = Contact.new(params[:reset_password])

              contact.name = "#{params[:reset_password][:name]}"
              contact.email = "#{params[:reset_password][:email]}"
              contact.subject = "#{params[:reset_password][:subject]}"
              contact.message = "#{params[:reset_password][:message]}"
              if contact.save
              
              ContactMailer.registrations_confirmation(contact).deliver
              redirect_to "/contacts",:notice => "We will reach you shortly.."
              end
            end
         else
           @title = "contacts"
         end
    
    end
    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def show
    @page = Page.find(params[:id])
    end
  
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    image_tag "images2/index_03.gif", :size => "375x55"
end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/pages/_button.html.erb
<p class="button">
  	<button class="button positive" type="submit">
		 Save
	</button>
	<%= link_to "Cancel", onclick="javascript:history.back()", :class => 'button negative' %>
    
  </p>

app/views/admin/pages/edit.html.erb
    <div id="content">

		<%= form_for [:admin, @page] , :html => { :multipart => true } do |f| %>
		  
		  <div id="breadcrumb">
		  	   <%= link_to "Pages", admin_pages_path %> &raquo; New
		  </div>
		 
		  <p>
		    <%= f.label :title %>
		    <%= f.text_field :title, :class => 'text' %>
		  </p>
		  
			p> <%= f.file_field :photo%>
			</p>
		 	 
      		<%= f.label(:delete_photo, 'Delete photo') %>
      		
      		<%= f.check_box(:delete_photo) %>
    	
			  <p>
		    <%= f.label :body %>
		    <%= f.text_area :body, :class => 'tiny_mce' %>
		  </p>
		  <p>
		    <%= f.label :keyword %>
		    <%= f.text_field :keyword, :class => 'text' %>
		  </p>

		  <p>
			<%= f.label :meta_description %>
		    <%= f.text_area :meta_description, :class => 'tiny_mce' %>

		  </p>
		  
		  <%= render :partial =>"button" %>
		
		<% end %>

app/views/admin/pages/index.html.erb
 <div id="content">
 	<p class='buttons'>
 		
 		<%= link_to  "Add Pages", new_admin_page_path, :class => 'button positive' %>
 		</p>
		<p class='clear'></p>
		   

			<table class="admintable">
			  <tr class="admintablehd">
			    <td width="25%">Title</td>
			    <td>Description</td>
			    <td width="27%" style="text-align: center !important;">Action</td>
			  </tr>
			
			<% @pages.each do |page| %>
			  <tr>
			    <td><%= page.title %></td>
			    <td><%= truncate(page.body, :length => 110).html_safe %> </td>
			    <td style="text-align: center !important;"> <%= link_to "Edit", edit_admin_page_path(page), :class=>'button positive' %> &nbsp;&nbsp; 
				<a href="/admin/pages/<%= page.id %>/delete" onclick="if(confirm('Are you sure you want to delete this page?'))  return true;  else  return false;" class="button negative" >Delete</a>
				</td>
			    
			  </tr>
			<% end %>
			</table>
			<br />
			
</div>

app/views/admin/pages/new.html.erb
    <div id="content">

		<%= form_for [:admin, @page] , :html => { :multipart => true } do |f| %>
		  
		  <div id="breadcrumb">
		  	   <%= link_to "Pages", admin_pages_path %> &raquo; New
		  </div>
		 
		  <p>
		    <%= f.label :title %>
		    <%= f.text_field :title, :class => 'text' %>
		  </p>
		  
			p> <%= f.file_field :photo%>
			</p>
		  
		  <p>
		    <%= f.label :body %>
		    <%= f.text_area :body, :class => 'tiny_mce' %>
		  </p>
		  <p>
		    <%= f.label :keyword %>
		    <%= f.text_field :keyword, :class => 'text' %>
		  </p>

		  <p>
			<%= f.label :meta_description %>
		    <%= f.text_area :meta_description, :class => 'tiny_mce' %>

		  </p>
		  
		  <%= render :partial =>"button" %>
		
		<% end %>


  </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolApp</title>
 <%= stylesheet_link_tag %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
   <%= javascript_include_tag "tiny_mce/tiny_mce" %>
  

	<script type="text/javascript">

     tinyMCE.init({  theme:"advanced",
					mode:"textareas",
    				editor_selector : "tiny_mce"
    				
    			});
   </script>
</head>
<body>
	<%= yield %>
<ul>
<li><% if controller.controller_name == 'pages' %>
	 <%= link_to "Pages", admin_pages_path, :class=>"active" %>
	  <% else %> 
	  <%= link_to "Pages", admin_pages_path %> 
	  <% end %></li>

  <li>
  	<% if controller.controller_name == 'contacts' %> 
  	<%= link_to "contacts", admin_contacts_path, :class=>"active" %> 
  	<% else %> 
  	<%= link_to "Contacts", admin_contacts_path %> 
  	<% end %>
  </li>
 	<% if admin_signed_in? %> 
	<%= link_to "Sign out", destroy_admin_session_path %> 
	<% else %> 
	<%= link_to "sign in", new_admin_session_path %> &nbsp; 
	<% end %>
  </li>	
</ul>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SchoolApp</title>
  <%= stylesheet_link_tag 'style'%> 
	
  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
</body>
</html>

app/views/pages/content.html.erb
<style type="text/css">
body{
	background-color: gray;
}
a:hover{background:url('http://www.addglitter.com/link-sparkle.gif');}
hr{background-image:url('http://www.addglitter.com/link-sparkle.gif'); }
</style><br />
<table width="780" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
	  <tr>
    <td colspan="2" align="left" valign="top"><table width="780" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="506" align="left" valign="top" height="40"><table width="506" border="0" cellspacing="0" cellpadding="0" >
          <tr>
            <td align="left" valign="top" style="padding-top:13px; padding-left:17px; padding-bottom:11px;"><%= link_to logo,root_path%></td>
          </tr>
          
          <tr>
            <td align="left" valign="top"><table width="506" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="180" align="left" valign="top"><%= image_tag "images2/index_08.gif", :size => "180x202" %></td>
                <td width="326" align="left" valign="top"><%= image_tag "images2/index_09.gif", :size => "326x202" %></td>
              </tr>
            </table></td>
            </tr>
             </table></td>
 <td width="274" align="left" valign="top" class = "cas">
    <table width="116" border="0" align="center" cellpadding="0" cellspacing="0">             
          <tr>
            <td align="left" valign="top" class="menu"><%= link_to "Home", root_path %></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/2">About us</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/3">Academics</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/6">Facilities</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/10">Careers</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><%= link_to "Contacts",contacts_path %></a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/12">Others</a></td>
          </tr>
            </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td colspan="2" align="left" valign="top" style="padding-top:18px; padding-bottom:22px; padding-left:20px;"><table width="740" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td width="524" align="left" valign="top"><table width="96%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td align="left" valign="top" class="heading" style="padding-bottom:8px;"></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce adipiscing consequat varius. Nulla sed semper neque. Maecenas eu sodales purus. Maecenas aliquam tellus eu risus consectetur lobortis. Nunc dapibus laoreet egestas. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse auctor rutrum mollis. Vivamus quis nisl in lacus posuere iaculis. Duis eu mattis sem. Praesent sit amet dui justo.

Curabitur sapien ante, consectetur ac iaculis non, dignissim id lorem. Donec suscipit felis id metus iaculis rutrum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent nisi nunc, interdum quis lobortis gravida, convallis eu libero. Pellentesque vitae lacus nec odio ultricies pulvinar in at nibh. Donec felis neque, porttitor vel ullamcorper sagittis, euismod sit amet arcu. Donec vitae arcu tellus, sed eleifend libero. Nullam accumsan, lorem quis malesuada commodo, tellus elit tristique metus, in lacinia lacus velit ut erat. Ut laoreet quam quis urna venenatis vestibulum. Donec sit amet metus mauris, non varius mi. Aenean molestie congue magna, id tempor quam rhoncus a. Nulla eget dui lorem, vitae porttitor felis. In at rutrum augue.

Etiam eleifend ultrices enim, in commodo enim volutpat hendrerit. Etiam lobortis turpis at augue fermentum commodo. Ut ornare tortor sit amet erat rhoncus varius. Donec tempor libero sed tellus condimentum eleifend iaculis erat egestas. Morbi semper lectus sed arcu tempus dapibus ut a ipsum. Duis tellus leo, consectetur ac laoreet in, feugiat a sapien. Suspendisse cursus pellentesque tortor nec luctus. Pellentesque eu magna eu odio varius tincidunt eu non eros. Mauris posuere nisl id risus pharetra sit amet pretium lorem luctus.

Nullam vulputate, diam et luctus rhoncus, ligula ante aliquet justo, nec hendrerit magna lacus sit amet arcu. Cras eget nunc est. Mauris vehicula posuere eleifend. Cras bibendum metus eget orci fringilla ultrices. Donec tempus ipsum commodo orci eleifend fermentum. Mauris eget ullamcorper leo. Morbi ornare facilisis urna, non commodo tellus dapibus quis. Quisque a mauris odio, quis ullamcorper ante. Sed felis ligula, fringilla rhoncus hendrerit in, aliquam id mi. Nam quis est id eros imperdiet sollicitudin ut rhoncus purus. Sed id sem enim. Integer tortor enim, rhoncus id aliquam ac, tincidunt sed velit. Aliquam fringilla orci sed mauris pretium iaculis tincidunt risus ultricies. Donec convallis eros pretium lacus sollicitudin ut euismod velit placerat. Vivamus viverra pretium velit, eget ultricies erat auctor vel. Curabitur rhoncus augue sit amet arcu pellentesque placerat.

Donec at diam metus, vel lacinia orci. Morbi metus libero, sagittis ut tincidunt sit amet, venenatis id justo. Maecenas ac quam massa, vel dignissim turpis. Integer vel feugiat quam. Quisque tempor est a lectus tempus et cursus elit feugiat. Donec quis massa nec metus tincidunt vehicula. Donec ultrices commodo mauris sed pharetra. Nunc velit mi, aliquam sit amet dictum sit amet, mattis quis enim.

Aenean vel magna augue, non facilisis quam. Vestibulum lobortis lacinia neque eu mollis. Nam pharetra mauris id leo dictum convallis. Mauris eget libero ac orci ullamcorper sollicitudin. In mollis, eros sed euismod sagittis, metus arcu viverra mauris, sit amet pulvinar tellus turpis ut metus. Nam vel massa a arcu porta gravida sit amet sit amet justo. Aenean ac diam vel magna tempor sollicitudin eget vitae sem. Praesent eu sem sit amet felis placerat volutpat vitae vitae felis. Nam et sodales orci. Cras non nibh felis, at porta mi. Quisque a lectus odio, id mattis neque. Suspendisse dignissim blandit leo eu tempus.

Donec pharetra, nibh nec rhoncus accumsan, risus turpis elementum justo, nec ultricies elit velit sit amet enim. Suspendisse rutrum venenatis leo ut iaculis. Maecenas tristique, diam quis dapibus sodales, sapien justo porttitor metus, vel tempor nisl lacus pharetra sapien. Cras consequat hendrerit massa sed feugiat. Fusce eget sem neque. Etiam nec nibh augue, at mollis magna. Suspendisse tincidunt hendrerit orci, at laoreet eros posuere nec. In ullamcorper, magna et eleifend faucibus, lectus metus imperdiet velit, at ultrices ante sem vel elit. Praesent ut arcu pulvinar magna varius condimentum quis ac quam. Donec at libero magna. Vestibulum scelerisque lectus nisl, ac posuere dui. Pellentesque eu turpis quis felis placerat bibendum non id purus. Pellentesque dolor est, auctor ornare vehicula sed, dapibus id leo. Vestibulum hendrerit massa a urna blandit aliquet.

Donec sed magna non odio sodales elementum sit amet et velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec purus sapien, dapibus et elementum a, tristique gravida enim. Sed eget enim at justo euismod feugiat sed placerat magna. Nullam risus massa, luctus eu commodo in, commodo eget nisl. Donec ut sem sit amet elit consectetur mattis a quis velit. Donec erat nunc, accumsan sit amet sollicitudin dapibus, dapibus faucibus libero. Suspendisse potenti. Duis eros augue, imperdiet non tincidunt eget, elementum sit amet quam. Praesent diam leo, hendrerit id elementum id, bibendum in dui. Sed malesuada lacinia felis in accumsan. Aliquam tempor faucibus tempus.

In hac habitasse platea dictumst. Mauris et turpis id dui bibendum posuere. Suspendisse sit amet leo at magna ultrices facilisis. Sed accumsan, nunc at sagittis consequat, dolor metus convallis nisi, id vestibulum erat dui ut erat. Suspendisse metus lacus, commodo at pulvinar in, vehicula et quam. Sed cursus enim quis est porta tempor. Donec sed ante sed massa porta porta. Nullam interdum velit nec felis blandit mattis. Quisque ultricies vulputate faucibus. Sed et ultricies erat. Fusce dictum pharetra vehicula. Vestibulum sed arcu eros, ut iaculis elit. Donec ut orci augue, ut vestibulum leo. Vestibulum sem dui, rhoncus ut viverra quis, ullamcorper sed urna. Phasellus ac metus est, quis viverra tortor. Cras dolor libero, fringilla quis pulvinar quis, aliquet quis nisi.

Fusce ornare, neque ac tincidunt rhoncus, odio sem ullamcorper neque, in rhoncus dolor nulla quis diam. Aliquam erat volutpat. Maecenas vulputate tincidunt sem vel venenatis. Vestibulum commodo, nisl eget tincidunt imperdiet, lacus nibh porta dui, non consequat nulla dui tincidunt dolor. Etiam cursus urna non massa consequat luctus. Phasellus in elit nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; 

<a href="content.html"></a></td>
          </tr>
        </table></td>
        <td width="216" align="left" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#F1F1F3">
          <tr>
            <td width="5%" align="left" valign="top"><%= image_tag "images2/index_12.gif", :size => "12x12" %></td>
            <td width="91%" align="left" valign="top">&nbsp;</td>
            <td width="4%" align="right" valign="top"><%= image_tag "images2/index_14.gif", :size => "12x12" %></td>
          </tr>
          <tr>
            <td align="left" valign="top">&nbsp;</td>
            <td align="left" valign="top"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td align="right" valign="top" style="padding-top:16px; padding-bottom:22px;"><table width="95%" border="0" align="right" cellpadding="0" cellspacing="0">
                  <tr>
                    <td align="right" valign="top" style="border-bottom:1px solid #E13000; padding-bottom:4px;"><%= image_tag "images2/index_23.gif", :size => "150x23" %></td>
                  </tr>
                </table></td>
              </tr>
              <tr>
                <td align="left" valign="top">&nbsp;</td>
              </tr>
            </table></td>
            <td align="left" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td align="left" valign="bottom"><%= image_tag "images2/index_62.gif", :size => "12x12" %></td>
            <td align="left" valign="top" style="padding-bottom:52px;"><table width="96%" border="0" align="right" cellpadding="0" cellspacing="0">
              <tr>
                <td width="42%" align="left" valign="top"><%= image_tag "images2/index_30.gif", :size => "60x65" %></td>
                <td width="58%" align="left" valign="top" class="righttext" style="padding-bottom:22px;"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more </a></td>
              </tr>
              <tr>
                <td align="left" valign="top"><%= image_tag "images2/index_49.gif", :size => "61x54" %></td>
                <td align="left" valign="top" class="righttext" style="padding-bottom:16px;"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more</a></td>
              </tr>
              <tr>
                <td align="left" valign="top"><%= image_tag "images2/index_54.gif", :size => "56x71" %></td>
                <td align="left" valign="top" class="righttext"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content">learn more</a></td>
              </tr>
            </table></td>
            <td align="right" valign="bottom"><%= image_tag "images2/index_63.gif", :size => "12x12" %></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td width="263" align="center" valign="top" bgcolor="#616C7C" class="copyright" style="border-right:1px solid #FFFFFF; padding-top:21px;">Copyright &copy; 2012 Kunal Infotech Pvt. Lmtd.<br /> 
    All Rights Reserved.</td>
    <td width="517" align="center" valign="top" bgcolor="#F1F1F3" style=" background-repeat:repeat-x; background-position:top; padding-top:26px; padding-bottom:17px;"><%= image_tag "images2/index_69.gif" %><pre class="footer"><%= link_to "Home", root_path %>   |   <a href="/pages/2">About us</a>   |   <a href="content.html">Site map</a>   |   <a href="/pages/3">Academics</a>   |<br />   <a href="content.html">News and Events</a>   |   <a href="content.html">Athletics</a></pre></td>
  </tr>
</table>