config/routes.rb
SchoolApp::Application.routes.draw do
  devise_for :admins
  
  root :to => "home#index"
  
  match '/pages/:id' => 'pages#show'
  
 
   match '/content' => 'pages#content'
  match '/pages/pages/:id' => 'pages#show'
  match '/admin/pages/:id/delete' => 'admin/pages#destroy'
  match '/admin/contacts/:id/delete' => 'admin/contacts#destroy'
  match '/home/:id' => 'home#contact'
   match '/contacts' => 'home#contact'
   
   namespace :admin do 
     match '/dashboard'   => "dashboard#index", :as => :root
          resources :pages
          resources :contacts
          match 'system/pages/photos/:id/' => 'admin/pages#destroy'
         
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable  
  attr_accessible :email, :password, :password_confirmation
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
end

app/models/page.rb
class Page < ActiveRecord::Base
 before_validation :clear_photo
  has_attached_file :photo, 
                    :default_url => '/assets/images.jpeg'
                    

 
    def delete_photo=(value)
    @delete_photo = !value.to_i.zero?
  end
  
  def delete_photo
    !!@delete_photo
  end
  alias_method :delete_photo?, :delete_photo
  
def clear_photo
  self.photo = nil if delete_photo? && !photo.dirty?
end

end

app/models/tiny_print.rb
class TinyPrint < ActiveRecord::Base
  
  has_attached_file :image,
    :convert_options => { :quality =>  4 },
    :styles => { :small_thumb => [ "50x50", :jpg ],
	               :medium_thumb => [ "100x100", :jpg ],
                 :large_thumb => [ "370x370", :jpg ],
	               :detail_preview => [ "450x338", :jpg ] },
    #:path => "/prints/:id/:style.:extension",
    :default_url => "/images/missing/prints/:style.png"

end

app/models/tiny_video.rb
class TinyVideo < ActiveRecord::Base
  
  has_attached_file :original
  #, :path => "videos/:original/:id.:extension",

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < Admin::BaseController
  before_filter :authenticate_admin!, :except => []
   def index
    @contacts = Contact.find(:all, :order => 'id desc')
  end
  
  def show
    @contact = Contact.find(params[:id])
        
  end
  
  def destroy
    @contact = Contact.find(params[:id])
   
    if @contact.destroy
      flash[:notice] = "Contact deleted successfully"
      redirect_to admin_contacts_path
    end
  end
end 

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  before_filter :authenticate_admin!, :except => []
  def index

  end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < Admin::BaseController
  
  before_filter :authenticate_admin!, :except => []
  def index
      @pages = Page.all
    end

    def new
      @page = Page.new
    end

    def create
      @page = Page.new(params[:page])
      if @page.save
        flash[:notice] = "Pages created successfully"
        redirect_to admin_pages_path
      else
        render :new
      end
    end
    
    def edit
      @page = Page.find(params[:id])
    end

    def update
      @page = Page.find(params[:id])
      if @page.update_attributes(params[:page])
        flash[:notice] = "Pages saved successfully"
        redirect_to admin_pages_path
      else
        render :new
      end
    end
    

    def destroy
      @page = Page.find(params[:id])
     
      if @page.destroy
        flash[:notice] = "Pages deleted successfully"
        redirect_to admin_pages_path
      end
      
    end
   
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :create

  def manage
    @attachments = "tiny_#{params[:media]}".classify.constantize.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10
    render :update do |page|
      page.replace_html :dynamic_images_list, :partial => 'show_attachment_list'
    end
  end
  


  def create
    @attachment = "tiny_#{params[:media]}".classify.constantize.new params[params[:media]]
    
    if @attachment.save
      GC.start
      responds_to_parent do
        render :update do |page|
          page << "upload_callback();"
        end
      end
    else
      responds_to_parent do
        render :update do |page|
          page.alert('Sorry, there was an error uploading the photo.')
        end
      end
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
      @contacts = Contact.find(:all)
    end

    def new
      @contact = Contact.new
    end

    def create
      @contact = Contact.new(params[:contact])
      respond_to do |format|
    if @contact.save
      format.html { redirect_to(@contact, :notice => 'contacts was successfully created.') }
      format.xml { render :xml => @contact, :status => :created, :location => @contact }
    else
      format.html { render :action => "new" }
      format.xml { render :xml => @contact.errors, :status => :unprocessable_entity }
    end
  end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
    
  def contact
    if request.post? and params[:reset_password]
            if contact = Contact.new(params[:reset_password])

              contact.name = "#{params[:reset_password][:name]}"
              contact.email = "#{params[:reset_password][:email]}"
              contact.subject = "#{params[:reset_password][:subject]}"
              contact.message = "#{params[:reset_password][:message]}"
              if contact.save
              
              ContactMailer.registrations_confirmation(contact).deliver
              redirect_to "/contacts",:notice => "We will reach you shortly.."
              end
            end
         else
           @title = "contacts"
         end
    
    end
    

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def show
    @page = Page.find(params[:id])
    end
  
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/helpers/admin/contacts_helper.rb
module Admin::ContactsHelper
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    image_tag "images2/index_03.gif", :size => "375x55"
end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/admin/contacts/index.html.erb
<div id="content">
  <p class='clear'></p>

			<table class="admintable">
			  <tr class="admintablehd">
			    <td width="25%">Name</td>
			    <td>Email</td>
			    <td>Subject</td>
			    <td>Message</td>
			    <td>Date/time</td>
			    <td width="27%" style="text-align: center !important;">Action</td> 
			  </tr>
			
			<% @contacts.each do |contact| %>
			  <tr>
			    <td><%= link_to contact.name, admin_contact_path(contact) %></td>
				<td><%= contact.email %></td>
				
				<td><%= contact.subject %></td>
			    <td><%= truncate(contact.message, :length => 90) %></td>
			    <td><%= contact.created_at.strftime("%B %d, %Y,%X") %></td>
			    <td style="text-align: center !important;"> 
				<a href="/admin/contacts/<%= contact.id %>/delete" onclick="if(confirm('Are you sure you want to delete this contact?'))  return true;  else  return false;" class="button negative" >Delete</a>
				</td>
			    
			  </tr>
			<% end %>
			
			</table>
			
			<br />
</div>

app/views/admin/contacts/show.html.erb
<div id="content">

<p><%= @contact.name %></p>
<p><%= @contact.subject %></p>
<p><%= decode_entities(@contact.message) %></p>

</div>

app/views/admin/dashboard/index.html.erb
<h1>Welcome to Admin panel</h1>

app/views/home/contact.html.erb
<style>
body{
	background-color: gray;
}
table{
	background-color: white;
}

</style>


<table width="780" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
	  <tr>
    <td colspan="2" align="left" valign="top">
    	<table width="780" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="506" align="left" valign="top"><table width="506" border="0" cellspacing="0" cellpadding="0" >
          <tr>
            <td align="left" valign="top" style="padding-top:13px; padding-left:17px; padding-bottom:11px;"><%= link_to logo,root_path%></td>
          </tr>
          
          <tr>
            <td align="left" valign="top"><table width="506" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="180" align="left" valign="top"><%= image_tag "images2/index_08.gif", :size => "180x202" %></td>
                <td width="326" align="left" valign="top"><%= image_tag "images2/index_09.gif", :size => "326x202" %></td>
              </tr>
            </table></td>
            </tr>
             </table></td>
 <td width="506"  align="left" valign="top" class="cas" >
 	
    <table class="a" width="116" border="0" align="center" cellpadding="0" cellspacing="0">  
    	          
          <tr>
            <td align="left" valign="top" class="menu"><%= link_to "Home", root_path %></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/2">About us</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/3">Academics</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/6">Facilities</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/10">Careers</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><%= link_to "Contacts",contacts_path %></td>
          </tr>
        <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/12">Others</a></td>
          </tr>
            </table></td>
      </tr>
    </table></td>
  </tr>
   <tr>
    <td colspan="2" align="left" valign="top" style="padding-top:18px; padding-bottom:22px; padding-left:20px;"><table width="740" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td width="524" align="left" valign="top"><table width="520" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td align="left" valign="top"><table width="95%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="2" align="left" valign="top" style="padding-bottom:16px;"><%= image_tag "images2/index_17.gif", :size => "303x22" %></td>
              </tr>
              <tr>
                <td colspan="2" align="left" valign="top" class="text"><h2>Contact<span> Get in touch with us</span> </h2>
<table cellpadding="5">
	 <%= form_for :reset_password, :html=>{:class=>'form', :id=>'contactform'} do |form| %>
	 
     <tr>
     <td><label for="name">Name:</label></td>
      <td><%= form.text_field :name %></td>
      </tr>
       <tr> 
         <td><label for="email">Email:</label>
    	 <td><%= form.text_field :email %>
       
        <tr><td>
             
         <label for="email">Subject:</label>
         <td><%= form.text_field :subject %>
       <tr><td>
         <label for="comments">Message:</label>
         <td class="a"><%= form.text_area :message, :rows => 4, :cols => 28 %>
        
               
        <p align="left" style="margin: 10px 0pt 0pt 2px;" ><%= submit_tag 'Send' %>
        <% end %>
        </table>
 </td>
              </tr>
              <tr>
                <td width="79%" align="left" valign="top" style="padding-top:20px; padding-bottom:16px;"><table width="94%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td align="left" valign="top" class="textback"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</td>
                  </tr>
                  <tr>
                    <td align="left" valign="top" class="textback">Nullam quis turpis eu libero varius vestibulum.</td>
                  </tr>
                  <tr>
                    <td align="left" valign="top" class="textback">In feugiat. Sed et turpis ac risus aliquet rhoncus.</td>
                  </tr>
                </table></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td align="left" valign="top"><table width="99%" border="0" cellspacing="0" cellpadding="0">
            
              </tr>

              
            </table></td>
          </tr>
        </table></td>
        <td width="216" align="left" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#F1F1F3">
          <tr>
            <td width="5%" align="left" valign="top"><%= image_tag "images2/index_12.gif", :size => "12x12" %></td>
            <td width="91%" align="left" valign="top">&nbsp;</td>
            <td width="4%" align="right" valign="top"><%= image_tag "images2/index_14.gif", :size => "12x12" %></td>
          </tr>
          <tr>
            <td align="left" valign="top">&nbsp;</td>
            <td align="left" valign="top"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td align="right" valign="top" style="padding-top:16px; padding-bottom:22px;"><table width="95%" border="0" align="right" cellpadding="0" cellspacing="0">
                  <tr>
                    <td align="right" valign="top" style="border-bottom:1px solid #E13000; padding-bottom:4px;"><%= image_tag "images2/index_23.gif", :size => "150x23" %></td>
                  </tr>
                </table></td>
              </tr>
              <tr>
                <td align="left" valign="top">&nbsp;</td>
              </tr>
            </table></td>
            <td align="left" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td align="left" valign="bottom"><%= image_tag "images2/index_62.gif", :size => "12x12" %></td>
            <td align="left" valign="top" style="padding-bottom:52px;"><table width="96%" border="0" align="right" cellpadding="0" cellspacing="0">
              <tr>
                <td width="42%" align="left" valign="top"><%= image_tag "images2/index_30.gif", :size => "60x65" %></td>
                <td width="58%" align="left" valign="top" class="righttext" style="padding-bottom:22px;"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more </a></td>
              </tr>
              <tr>
                <td align="left" valign="top"><%= image_tag "images2/index_49.gif", :size => "61x54" %></td>
                <td align="left" valign="top" class="righttext" style="padding-bottom:16px;"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more</a></td>
              </tr>
              <tr>
                <td align="left" valign="top"><%= image_tag "images2/index_54.gif", :size => "56x71" %></td>
                <td align="left" valign="top" class="righttext"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more</a></td>
              </tr>
            </table></td>
            <td align="right" valign="bottom"><%= image_tag "images2/index_63.gif", :size => "12x12" %></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td width="263" align="center" valign="top" bgcolor="#616C7C" class="copyright" style="border-right:1px solid #FFFFFF; padding-top:21px;">Copyright &copy; 2012 Kunal Infotech Pvt. Lmtd.<br /> 
    All Rights Reserved.</td>
    <td width="517" align="center" valign="top" bgcolor="#F1F1F3" style=" background-repeat:repeat-x; background-position:top; padding-top:26px; padding-bottom:17px;"><%= image_tag "images2/index_69.gif" %><pre class="footer"><%= link_to "Home", root_path %>   |   <a href="/pages/2">About us</a>   |   <a href="content.html">Site map</a>   |   <a href="/pages/3">Academics</a>   |<br />   <a href="content.html">News and Events</a>   |   <a href="content.html">Athletics</a></pre></td>
  </tr>
</table>

<

app/views/home/index.html.erb
<style type="text/css">
body{
	background-color: gray;
}
a:hover{background:url('http://www.addglitter.com/link-sparkle.gif');}
hr{background-image:url('http://www.addglitter.com/link-sparkle.gif'); }
</style><br />


<table width="780" border="0" align="center" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
	  <tr>
    <td colspan="2" align="left" valign="top">
    	<table width="780" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="506" align="left" valign="top"><table width="506" border="0" cellspacing="0" cellpadding="0" >
          <tr>
            <td align="left" valign="top" style="padding-top:13px; padding-left:17px; padding-bottom:11px;"><%= link_to logo,root_path%></td>
          </tr>
          
          <tr>
            <td align="left" valign="top"><table width="506" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="180" align="left" valign="top"><%= image_tag "images2/index_08.gif", :size => "180x202" %></td>
                <td width="326" align="left" valign="top"><%= image_tag "images2/index_09.gif", :size => "326x202" %></td>
              </tr>
            </table></td>
            </tr>
             </table></td>
 <td width="506"  align="left" valign="top" class="cas" >
 	
    <table class="a" width="116" border="0" align="center" cellpadding="0" cellspacing="0">  
    	          
          <tr>
            <td align="left" valign="top" class="menu"><%= link_to "Home", root_path %></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/2">About us</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/3">Academics</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/6">Facilities</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/10">Careers</a></td>
          </tr>
          <tr>
            <td align="left" valign="top" class="menu"><%= link_to "Contacts",contacts_path %></td>
          </tr>
        <tr>
            <td align="left" valign="top" class="menu"><a href="/pages/12">Others</a></td>
          </tr>
            </table></td>
      </tr>
    </table></td>
  </tr>
   <tr>
    <td colspan="2" align="left" valign="top" style="padding-top:18px; padding-bottom:22px; padding-left:20px;"><table width="740" border="0" align="left" cellpadding="0" cellspacing="0">
      <tr>
        <td width="524" align="left" valign="top"><table width="520" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td align="left" valign="top"><table width="95%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="2" align="left" valign="top" style="padding-bottom:16px;"><%= image_tag "images2/index_17.gif", :size => "303x22" %></td>
              </tr>
              <tr>
                <td colspan="2" align="left" valign="top" class="text">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam quis turpis eu libero varius vestibulum. In feugiat. Sed et turpis ac risus aliquet rhoncus. Nam cursus molestie metus. Aliquam ac neque nec leo condimentum lobortis.</td>
              </tr>
              <tr>
                <td width="79%" align="left" valign="top" style="padding-top:20px; padding-bottom:16px;"><table width="94%" border="0" cellspacing="0" cellpadding="0">
                  <tr>
                    <td align="left" valign="top" class="textback"> Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</td>
                  </tr>
                  <tr>
                    <td align="left" valign="top" class="textback">Nullam quis turpis eu libero varius vestibulum.</td>
                  </tr>
                  <tr>
                    <td align="left" valign="top" class="textback">In feugiat. Sed et turpis ac risus aliquet rhoncus.</td>
                  </tr>
                </table></td>
                <td width="21%" align="left" valign="top"><%= image_tag "animated-gifs-school-08.gif", :size => "112x110" %></td>
              </tr>
            </table></td>
          </tr>
          <tr>
            <td align="left" valign="top"><table width="99%" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td colspan="2" align="left" valign="top" style="padding-bottom:22px;"><%= image_tag "images2/index_45.gif", :size => "211x22" %></td>
              </tr>
              <tr>
                <td colspan="2" align="left" valign="top" class="text" style="padding-right:28px;">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam quis turpis eu libero varius vestibulum. In feugiat. Sed et turpis ac risus aliquet rhoncus. Nam cursus molestie metus. Aliquam ac neque nec leo condimentum lobortis.<br />
                  <br />
                  <div class="text" style="padding-bottom:15px;"><a href="content.html">learn more</a></div></td>
              </tr>
              <tr>
                <td width="47%" align="left" valign="top"><%= image_tag "images2/index_57.gif", :size => "255x103" %></td>
                <td width="53%" align="right" valign="top"><%= image_tag "images2/index_59.gif", :size => "255x103" %></td>
              </tr>
            </table></td>
          </tr>
        </table></td>
        <td width="216" align="left" valign="top"><table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#F1F1F3">
          <tr>
            <td width="5%" align="left" valign="top"><%= image_tag "images2/index_12.gif", :size => "12x12" %></td>
            <td width="91%" align="left" valign="top">&nbsp;</td>
            <td width="4%" align="right" valign="top"><%= image_tag "images2/index_14.gif", :size => "12x12" %></td>
          </tr>
          <tr>
            <td align="left" valign="top">&nbsp;</td>
            <td align="left" valign="top"><table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
              <tr>
                <td align="right" valign="top" style="padding-top:16px; padding-bottom:22px;"><table width="95%" border="0" align="right" cellpadding="0" cellspacing="0">
                  <tr>
                    <td align="right" valign="top" style="border-bottom:1px solid #E13000; padding-bottom:4px;"><%= image_tag "images2/index_23.gif", :size => "150x23" %></td>
                  </tr>
                </table></td>
              </tr>
              <tr>
                <td align="left" valign="top">&nbsp;</td>
              </tr>
            </table></td>
            <td align="left" valign="top">&nbsp;</td>
          </tr>
          <tr>
            <td align="left" valign="bottom"><%= image_tag "images2/index_62.gif", :size => "12x12" %></td>
            <td align="left" valign="top" style="padding-bottom:52px;"><table width="96%" border="0" align="right" cellpadding="0" cellspacing="0">
              <tr>
                <td width="42%" align="left" valign="top"><%= image_tag "images2/index_30.gif", :size => "60x65" %></td>
                <td width="58%" align="left" valign="top" class="righttext" style="padding-bottom:22px;"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more </a></td>
              </tr>
              <tr>
                <td align="left" valign="top"><%= image_tag "images2/index_49.gif", :size => "61x54" %></td>
                <td align="left" valign="top" class="righttext" style="padding-bottom:16px;"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more</a></td>
              </tr>
              <tr>
                <td align="left" valign="top"><%= image_tag "images2/index_54.gif", :size => "56x71" %></td>
                <td align="left" valign="top" class="righttext"><span style="color:#096A9C;"><strong>Lorem ipsum</strong></span><br />
                  Solor sit amet, consectetuer adipi lobortis.<br />
<br />
<a href="content.html">learn more</a></td>
              </tr>
            </table></td>
            <td align="right" valign="bottom"><%= image_tag "images2/index_63.gif", :size => "12x12" %></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td width="263" align="center" valign="top" bgcolor="#616C7C" class="copyright" style="border-right:1px solid #FFFFFF; padding-top:21px;">Copyright &copy; 2012 Kunal Infotech Pvt. Lmtd.<br /> 
    All Rights Reserved.</td>
    <td width="517" align="center" valign="top" bgcolor="#F1F1F3" style=" background-repeat:repeat-x; background-position:top; padding-top:26px; padding-bottom:17px;"><%= image_tag "images2/index_69.gif" %><pre class="footer"><%= link_to "Home", root_path %>   |   <a href="/pages/2">About us</a>   |   <a href="content.html">Site map</a>   |   <a href="/pages/3">Academics</a>   |<br />   <a href="content.html">News and Events</a>   |   <a href="content.html">Athletics</a></pre></td>
  </tr>
</table>